Feature controllers specs
Richie9000/Blog-app pull request #2
Opened 2021-10-29 16:59 UTC by Richie9000

Add RSpec as a gem to the project.
    Create a Request spec file for  controllers.
    Check:
        If response status was correct.
        If a correct template was rendered.
        If the response body includes correct placeholder text.

2021-10-29 18:07 UTC, oxenprogrammer requested changes
Hi @Richie9000, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-29 18:07 UTC, oxenprogrammer commented on README.md
> +- Testing
**Changes Required**
- [ ] You're missing some critical steps to run the app. Please let us include all the steps required to run the app successfully. When I run the `rspec` I get the below error.

![role](https://user-images.githubusercontent.com/7220167/139481944-acc359a6-8823-42c7-9d55-76c1ec9ca810.png)

2021-10-29 18:38 UTC, Richie9000 commented on README.md
> +- Testing
FATAL: role "emmisteel" does not exist, that's a a problem with your db.

2021-10-29 18:53 UTC, Richie9000 commented on README.md
> +- Testing
![Screenshot from 2021-10-29 13-52-05](https://user-images.githubusercontent.com/65680567/139487509-7e837030-c0ca-4900-be8e-84722755cf9c.png)

2021-10-29 18:55 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED ✔🎉**
Hello @Richie9000 👋🏽
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-29 18:55 UTC, merged

2021-10-30 10:30 UTC, oxenprogrammer commented on README.md
> +- Testing
- [ ] You're right. I was simply pointing out that you needed to include a clear step on how to setup the database in the README file. Remember the README is your living documentation and a contributor should pick up easily by simply reading the README file else we are leaving things to assumptions. Otherwise well done getting your project approved.